### ISSUE TITLE
GSS Google Spreadsheet using disabled API, may need to use OAuth2

### ISSUE THREAD

**Issue by padelt** [jpmens/mqttwarn#163]
I tried to use `services/gss.py` to add rows to a Google Spreadsheet from mqttwarn.
It seems that the [ClientLogin API](https://developers.google.com/api-client-library/java/google-api-java-client/client-login) used is both deprecated and disabled.

> Important: Do not use ClientLogin for new applications. Instead, use the more secure OAuth 2.0 authentication protocol. ClientLogin is a deprecated authentication protocol, which is being turned down on April 20, 2015. At that time, ClientLogin requests will no longer be answered.

It seems that using the OAuth 2.0 is now necessary.
https://developers.google.com/api-client-library/python/guide/aaa_overview

How to raise the problem:

All non-commented lines from `mqttwarn.ini`:
```
[defaults]
hostname     = 'localhost'  ; default
port         = 8883
username     = 'USERNAME'
password     = 'PASSWORD'
clientid     = 'mqttwarn'
lwt          = 'clients/mqttwarn'
skipretained = False
cleansession = False
protocol     = 3

ca_certs = '/volume/config/tls/ca.crt'
tls_insecure = True
tls_version = 'tlsv1'
logformat = '%(asctime)-15s %(levelname)-5s [%(module)s] %(message)s'
logfile   = '/volume/log/mqttwarn.log'
loglevel     = DEBUG
functions = 'samplefuncs'
launch   = file, log, gss

[config:file]
append_newline = True
targets = {
    'owntracks'  : ['/volume/log/mqtt-owntracks.log'],
    '_owntracks' : ['/volume/log/mqtt-owntracks-underscore.log'],
    'mqttwarn'   : ['/volume/log/mqttwarn.err'],
    }

[config:log]
targets = {
    'info'   : [ 'info' ],
    'warn'   : [ 'warn' ],
    'crit'   : [ 'crit' ],
    'error'  : [ 'error' ]
  }

[failover]
targets = log:error, file:mqttwarn

[hello/1]
targets = log:info
format = u'{name}: {number} => {_dthhmm}'

[owntracks-location]
topic = owntracks/+/+
targets = log:info, file:owntracks
datamap = OwnTracksTopic2Data()
format  = OwnTracksConvert()

[owntracks-location2]
topic = _owntracks/#
targets = log:info, file:owntracks

[owntracks-battery]
topic = owntracks/+/+
targets = log:info, file:owntracks
datamap = OwnTracksTopic2Data()
filter  = OwnTracksBattFilter()
format  = {username}'s phone battery is getting low ({batt}%)

[config:gss]
username    = username@googlemail.com
password    = GMAILPASSWORD
targets     = {
               # spreadsheet_key                               # worksheet_id
    'owntracks-pa': [ '1FZGavI3XXXXXXXXXXqJ54ROH7puXXXXXXXXXA-ikXXk',  'od6']
    }

[owntracks-beacon]
topic = owntracks/+/+/event
targets = gss:owntracks-pa
```

After adding some instrumentation output to `services/gss.py` I can see such a stacktrace:
```
2016-01-01 20:59:32,108 WARNING [gss] Error adding row to spreadsheet 1FZGavI3XXXXXXXXXXqJ54ROH7puXXXXXXXXXA-ikXXk [od6]: mismatched tag: line 945, column 4
2016-01-01 20:59:32,159 WARNING [gss] Traceback: Traceback (most recent call last):
  File "services/gss.py", line 55, in plugin
    client.InsertRow(row, spreadsheet_key, worksheet_id)
  File "/usr/local/lib/python2.7/dist-packages/gdata/spreadsheet/service.py", line 339, in InsertRow
    converter=gdata.spreadsheet.SpreadsheetsListFromString)
  File "/usr/local/lib/python2.7/dist-packages/gdata/service.py", line 1236, in Post
    media_source=media_source, converter=converter)
  File "/usr/local/lib/python2.7/dist-packages/gdata/service.py", line 1347, in PostOrPut
    redirects_remaining - 1, media_source, converter=converter)
  File "/usr/local/lib/python2.7/dist-packages/gdata/service.py", line 1329, in PostOrPut
    return converter(result_body)
  File "/usr/local/lib/python2.7/dist-packages/gdata/spreadsheet/__init__.py", line 377, in SpreadsheetsListFromString
    xml_string)
  File "/usr/local/lib/python2.7/dist-packages/atom/__init__.py", line 93, in optional_warn_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/atom/__init__.py", line 127, in CreateClassFromXMLString
    tree = ElementTree.fromstring(xml_string)
  File "<string>", line 124, in XML
ParseError: mismatched tag: line 945, column 4
```

On stdout I can see this:
```
send: 'POST https://www.google.com/accounts/ClientLogin HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: www.google.com\r\nContent-Length: 111\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: 'Passwd=XXXX&source=mqttwarn&service=wise&Email=USERNAME%40googlemail.com&accountType=HOSTED_OR_GOOGLE'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Content-Type: text/plain
header: X-Frame-Options: DENY
header: Cache-control: no-cache, no-store
header: Pragma: no-cache
header: Expires: Mon, 01-Jan-1990 00:00:00 GMT
header: Date: Fri, 01 Jan 2016 21:19:32 GMT
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Content-Length: 65
header: Server: GSE
header: Alternate-Protocol: 443:quic,p=1
header: Alt-Svc: quic="www.google.com:443"; ma=600; v="30,29,28,27,26,25",quic=":443"; ma=600; v="30,29,28,27,26,25"
```

**Comment by jpmens** [comment]
Closed via https://github.com/jpmens/mqttwarn/pull/164
