### ISSUE TITLE
paho-mqtt 1.3.0 connect to MQ but exit on on_connect() callback

### ISSUE THREAD

**Issue by lrizzi** [jpmens/mqttwarn#251]
I've just tried a fresh installation of mqttwarn, from pip I get the paho-mqtt version 1.3.0, mqttwarn start and establish the connection with the broker then on callback of on_connect() it exit.

Here an example:
```./mqttwarn.py 
Traceback (most recent call last):
  File "./mqttwarn.py", line 1103, in <module>
    connect()
  File "./mqttwarn.py", line 1060, in connect
    mqttc.loop_forever()
  File "/srv/mqttwarn/lib/python2.7/site-packages/paho/mqtt/client.py", line 1470, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/srv/mqttwarn/lib/python2.7/site-packages/paho/mqtt/client.py", line 995, in loop
    rc = self.loop_read(max_packets)
  File "/srv/mqttwarn/lib/python2.7/site-packages/paho/mqtt/client.py", line 1273, in loop_read
    rc = self._packet_read()
  File "/srv/mqttwarn/lib/python2.7/site-packages/paho/mqtt/client.py", line 1838, in _packet_read
    rc = self._packet_handle()
  File "/srv/mqttwarn/lib/python2.7/site-packages/paho/mqtt/client.py", line 2291, in _packet_handle
    return self._handle_connack()
  File "/srv/mqttwarn/lib/python2.7/site-packages/paho/mqtt/client.py", line 2349, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
TypeError: on_connect() takes exactly 3 arguments (4 given)
```

According to the paho-mqtt documentation the arg "flags" is missing on the on_connect() definitions, adding that argument fix the problem, but I don't know if it make sense to handle the response flags from the broker, maybe for debug purpose.

To reproduce: upgrade to paho-mqtt version 1.3.0
Workaround: downgrade to paho-mqtt version 1.2.3

**Comment by jpmens** [comment]
Note to self: [this is the Paho commit](https://github.com/eclipse/paho.mqtt.python/commit/1ce831cfd4d0197212be0367020fa3be2d1fc3e8)
