### ISSUE TITLE
TypeError: on_connect() takes exactly 3 arguments (4 given)

### ISSUE THREAD

**Issue by josephzajdler** [jpmens/mqttwarn#253]
Cloned to Raspberry PI,
Followed installation instructions,
And I get this error.
I'm Not Happy.

sudo python mqttwarn.py
Traceback (most recent call last):
  File "mqttwarn.py", line 919, in <module>
    connect()
  File "mqttwarn.py", line 879, in connect
    mqttc.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1470, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 995, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1273, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1838, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2291, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2349, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
TypeError: on_connect() takes exactly 3 arguments (4 given)

**Comment by lrizzi** [comment]
Please, check for the closed issue #251 

upgrade your paho-mqtt to version 1.3.0

**Comment by josephzajdler** [comment]
I am on version 1.3.0

**Comment by jpmens** [comment]
Show me what this prints

```
$ python
>>> import paho.mqtt
>>> paho.mqtt.__version__
```

**Comment by josephzajdler** [comment]
'1.3.0'
