### ISSUE TITLE
on_connect() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by knsg0d** [jpmens/mqttwarn#273]
client.loop_forever()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/paho/mqtt/client.py", line 2311, in _packet_handle
    return self._handle_connack()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/paho/mqtt/client.py", line 2372, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
TypeError: on_connect() takes 3 positional arguments but 4 were given

**Comment by jpmens** [comment]
Please don't use issue titles to tell a story: keep it short and sweet.

Your version of Paho MQTT is too old. Unfortunately the project changed the signature of the function [a while back](https://github.com/jpmens/mqttwarn/issues/251) and we went along with that. You'll have to upgrade your Paho MQTT library.

**Comment by knsg0d** [comment]
Thanks for your advice jpmens i will repair about the issue title and try updating  Paho MQTT library.

**Comment by knsg0d** [comment]
pip install paho-mqtt
Requirement already satisfied: paho-mqtt in /usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg

**Comment by knsg0d** [comment]
my paho-mqtt version is already update and I don't know what is wrong jpmens 
Please help me with this!!!

**Comment by jpmens** [comment]
pip install --upgrade paho-mqtt

**Comment by knsg0d** [comment]
After i running this command 
the result is already updated 
$ pip install --upgrade paho-mqtt
Requirement already up-to-date: paho-mqtt in /usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg

**Comment by knsg0d** [comment]
but this time I running test123.py it different error
-------------------------------------------------------------------
Traceback (most recent call last):
  File "test123.py", line 24, in <module>
    client.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 2305, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 2500, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 2647, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "test123.py", line 12, in on_message
    print(msg.topic+" "+str(msg.payload))
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 360, in topic
    return self._topic.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 31: invalid continuation byte
------------------------------------------------------------------------------------------------------
