### ISSUE TITLE
Installing mqttwarn through pip croaks with UnicodeDecodeError

### ISSUE THREAD

**Issue by dlangille** [jpmens/mqttwarn#386]
When building 0.11.3 as found at https://pypi.org/project/mqttwarn/, I hit this error:

```
===>  Configuring for py36-mqttwarn-0.11.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 7, in <module>
    README = open(os.path.join(here, 'README.rst')).read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4963: ordinal not in range(128)
*** Error code 1
```

I have encountered this on other applications, but I do not recall the fix.  To get around this and proceed with the build, I did this:

```
rm README.rst
touch README.rst
```

**Comment by dlangille** [comment]
woah... that's a lot of new dependencies.

```
New packages to be INSTALLED:
	py36-mqttwarn: 0.11.3
	py36-requests: 2.22.0
	py36-chardet: 3.0.4_1
	py36-certifi: 2019.9.11
	py36-urllib3: 1.22,1
	py36-openssl: 19.0.0
	py36-cryptography: 2.6.1
	py36-six: 1.12.0
	py36-cffi: 1.13.2
	py36-pycparser: 2.19
	py36-asn1crypto: 0.24.0
	py36-pysocks: 1.7.1
	py36-idna: 2.8
	py36-paho-mqtt: 1.4.0
	py36-docopt: 0.6.2_1
	py36-attrs: 19.1.0
	py36-Jinja2: 2.10.1
	py36-MarkupSafe: 1.1.1
	py36-Babel: 2.7.0
	py36-pytz: 2019.3,1

```

**Comment by dlangille** [comment]
```
2019-11-25 01:30:20,067 INFO success: mqttwarn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-25 01:30:20,067 INFO exited: mqttwarn (exit status 1; not expected)
2019-11-25 01:30:20,068 DEBG received SIGCHLD indicating a child quit
2019-11-25 01:30:21,134 INFO spawned: 'mqttwarn' with pid 23881
2019-11-25 01:30:21,387 DEBG 'mqttwarn' stderr output:
Traceback (most recent call last):
  File "/usr/local/bin/mqttwarn", line 11, in <module>
    load_entry_point('mqttwarn==0.11.3', 'console_scripts', 'mqttwarn')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/mqttwarn/commands.py", line 12, in <module>
    from mqttwarn.configuration import load_configuration
  File "/usr/local/lib/python3.6/site-packages/mqttwarn/configuration.py", line 8, in <module>
    from ConfigParser import RawConfigParser, NoOptionError
ModuleNotFoundError: No module named 'ConfigParser'
```

What is it looking for?

```
[dan@mqtt01:~] $ python
Python 3.6.9 (default, Nov  8 2019, 18:03:54) 
[GCC 4.2.1 Compatible FreeBSD Clang 8.0.1 (tags/RELEASE_801/final 366581)] on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>> import ConfigParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ConfigParser'
>>> import configparser
>>> 

```

**Comment by dlangille** [comment]
I changed that to `configparser`, now it's 

`ModuleNotFoundError: No module named 'Queue`

**Comment by dlangille** [comment]
I changed Queue to queue, we are now running.

**Comment by dlangille** [comment]
It is having trouble loading up the services:

```
2019-11-25 01:56:14,836 ERROR    [mqttwarn.core            ] Unable to load service "file" from file "/usr/local/lib/python3.6/site-packages/mqttwarn/services/file.py": Unicode-objects must be encoded before hashing
2019-11-25 01:56:14,836 ERROR    [mqttwarn.core            ] Unable to load service "pushover" from file "/usr/local/lib/python3.6/site-packages/mqttwarn/services/pushover.py": Unicode-objects must be encoded before hashing
2019-11-25 01:56:14,837 ERROR    [mqttwarn.core            ] Unable to load service "log" from file "/usr/local/lib/python3.6/site-packages/mqttwarn/services/log.py": Unicode-objects must be encoded before hashing
```

But I find these installed by the package:

```
$ pkg info -l py36-mqttwarn | grep file
	/usr/local/lib/python3.6/site-packages/mqttwarn/services/__pycache__/file.cpython-36.opt-1.pyc
	/usr/local/lib/python3.6/site-packages/mqttwarn/services/__pycache__/file.cpython-36.pyc
	/usr/local/lib/python3.6/site-packages/mqttwarn/services/file.py
```

That's it for today.

**Comment by jpmens** [comment]
Thanks for your report, @dlangille. Please note that we're not as yet Python3 capable, which is why you're seeing all those errors. The version on PyPi still requires Python2.

**Comment by dlangille** [comment]
The version on PyPi does seem to almost work with Python 3.6 - much progress has been made.

**Comment by amotl** [comment]
Dear Dan,

7411a39  might fix the installation issue re. `README.rst` for you. Also, 40fa69a5 finally brings mqttwarn way closer to Python3 (#336).

We will be happy to hear back from you about the outcome.

With kind regards,
Andreas.
