### ISSUE TITLE
Conflict between Python 3 http module and http service

### ISSUE THREAD

**Issue by mortenf** [jpmens/mqttwarn#436]
When trying to execute a service plugin file directly, as e.g. [suggested by the tootpaste service](https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#tootpaste), Python gets confused by the http service plugin file:

`ModuleNotFoundError: No module named 'http.client'; 'http' is not a package`

Apparently, the Python 3 package http is "overridden" by the http service plugin.

I'm not sure how this should be fixed - only real solution seems to be renaming the http service, which will surely break things out there.

Executing a service plugin file directly is useful for initialisation purposes, but also for development/testing.

**Comment by amotl** [comment]
Dear Morten,

> Executing a service plugin file directly is useful for initialisation purposes, but also for development/testing.

I hear you. You will be able to [launch service plugins directly](https://github.com/jpmens/mqttwarn#running-notification-plugins) by invoking:
```
mqttwarn --plugin=http --data='{"message": "Hello world", "addrs": ["GET", "http://example.org/", null]}'
```

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

the problem can be reproduced like this:
```shell
$ python mqttwarn/services/tootpaste.py 'https://masto.io' 'jane@example.org' 'xafa5280890' warnme su03-a.client su03-a.user
```

```python
Traceback (most recent call last):
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/mqttwarn/services/tootpaste.py", line 13, in <module>
    from mastodon import Mastodon
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/mastodon/__init__.py", line 1, in <module>
    from mastodon.Mastodon import Mastodon, AttribAccessDict, MastodonError, MastodonVersionError, MastodonIllegalArgumentError, MastodonIOError, MastodonFileNotFoundError, MastodonNetworkError, MastodonAPIError, MastodonNotFoundError, MastodonUnauthorizedError, MastodonRatelimitError, MastodonMalformedEventError, MastodonServerError, MastodonInternalServerError, MastodonBadGatewayError, MastodonServiceUnavailableError, MastodonGatewayTimeoutError
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/mastodon/Mastodon.py", line 13, in <module>
    import requests
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/urllib3/exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 234, in create_module
    return self.load_module(spec.name)
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 209, in load_module
    mod = mod._resolve()
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 118, in _resolve
    return _import_module(self.mod)
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 87, in _import_module
    __import__(name)
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/mqttwarn/services/http.py", line 11, in <module>
    import urllib.request, urllib.parse, urllib.error
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 88, in <module>
    import http.client
ModuleNotFoundError: No module named 'http.client'; 'http' is not a package
```

So, indeed, we are tripped by [1,2]. The question now is, how can we improve the situation?

With kind regards,
Andreas.

[1] https://stackoverflow.com/questions/24880147/import-http-client-encouter-import-error-with-python-3-4-1
[2] https://github.com/microsoft/Cognitive-SpeakerRecognition-Python/issues/7

**Comment by jpmens** [comment]
Looks like renaming the service would be the most reasonable, even though there will be breakage?

**Comment by amotl** [comment]
#500 does it without breakage.
