### ISSUE TITLE
[fbchat] Update fbchat service with last version v2.0.0a5

### ISSUE THREAD

**Issue by orzechszek** [jpmens/mqttwarn#485]
Please make needed updates for fbchat service to cover changes in last version: https://github.com/fbchat-dev/fbchat - v2.0.0a5

**Comment by amotl** [comment]
Dear @orzechszek,

thank you for writing in. Can I humbly ask you to submit a corresponding patch? We will be very happy to accept any patches which improve the situation on this.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

according to [1], the development/release of the upcoming version 2.0.0 has stalled a bit. So, I figure the current implementation would be still functional?

mqttwarn can be installed with the `fbchat` package by invoking:

```shell
pip install mqttwarn[fbchat]
```

With kind regards,
Andreas.

[1] https://pypi.org/project/fbchat/#history

**Comment by orzechszek** [comment]
Hi,
I have a problem with runinng fbchat module with version 2.0.0a5. I'm getting:

Cannot invoke service for `fbchat'
Traceback (most recent call last):
  File "/opt/mqttwarn/lib/python3.8/site-packages/mqttwarn/core.py", line 502, in processor
    module = service_plugins[service]['module']
KeyError: 'module'

**Comment by amotl** [comment]
Hi again,

while I can't verify the whole process, I believe the most recent stable version, `fbchat==1.9.7` could still work. On my machine, it only croaks because of wrong credentials, where I am lacking to provide real ones.

On the other hand, when upgrading `fbchat` by invoking `pip install fbchat==2.0.0a5`, mqttwarn would error out with
```python
2021-09-29 18:53:02,773 ERROR    [mqttwarn.core             ] Unable to load service "fbchat" from file "/Users/amo/dev/daq-tools/sources/mqttwarn/mqttwarn/services/fbchat.py": No module named 'fbchat.models'
Traceback (most recent call last):
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/mqttwarn/core.py", line 568, in load_services
    service_plugins[service]['module'] = load_module_from_file(modulefile)
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/mqttwarn/util.py", line 164, in load_module_from_file
    return imp.load_source(digest, path, fp)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/amo/dev/daq-tools/sources/mqttwarn/mqttwarn/services/fbchat.py", line 9, in <module>
    from fbchat.models import *
ModuleNotFoundError: No module named 'fbchat.models'
2021-09-29 18:53:02,777 CRITICAL [mqttwarn.core             ] Unable to load service "fbchat"
```

That obviously shows that the current implementation of the service adapter, `mqttwarn/services/fbchat.py`, is not compatible with `fbchat>=2.0` yet, right?

Maybe you can outline what is wrong with the stable version `fbchat==1.9.7`?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @orzechszek,

https://github.com/fbchat-dev/fbchat/commit/916a14062d added an "unmaintained" notice, where https://github.com/fbchat-dev/fbchat/issues/613 has some further discussions.

From there, I also discovered https://github.com/tulir/fbchat-asyncio, https://github.com/JuniorJPDJ/messenger_api, and https://github.com/Schmavery/facebook-chat-api.

Apparently, Facebook now has an official API for chat bots, the [»Meta« Messenger Platform](https://developers.facebook.com/docs/messenger-platform). It looks like the HTTP calls outlined on [1,2] would be the right way to submit messages these days.

With kind regards,
Andreas.

[1] https://developers.facebook.com/docs/messenger-platform/send-messages
[2] https://developers.facebook.com/docs/messenger-platform/reference/send-api

/cc @przemas

**Comment by amotl** [comment]
Hi again,

as I don't see any future and sense in making the `fbchat` module work again, we may want to remove it altogether, right? In order to carry on the discussion about a successor service plugin, I've just created #579.

Therefore, I am closing this issue now. Feel free to reopen if you think it is not appropriate.

With kind regards,
Andreas.
